rgbd_odom:
  description: "Localization with visual rgbd odometry - output of rgbd_odometry RTAB-Map node"
  localization_launch_args: [
    "rgbd_odom:=true", "rtabmap:=false", "realsense:=false", "ekf:=false", "navsat_transform:=false"
  ]
  pose_estimate_topic: "/rgbd_odom"
  rl_config:
    ekf_odom:
      ros__parameters:
        odom0: /rgbd_odom
        odom0_config: [false,  false,  false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 20
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: true
ekf_rgbd_odom:
  description: "Localization with EKF fusion with rgbd odometry"
  localization_launch_args: [
    "rgbd_odom:=true", "rtabmap:=false", "realsense:=false", "ekf:=true", "navsat_transform:=false"
  ]
  pose_estimate_topic: "/odometry/filtered"
  rl_config:
    ekf_odom:
      ros__parameters:
        odom0: /rgbd_odom
        odom0_config: [false,  false,  false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 20
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: true

ekf_rgbd_odom_imu:
  description: "Localization with EKF fusion with rgbd odometry + IMU"
  localization_launch_args: [
    "rgbd_odom:=true", "rtabmap:=false", "realsense:=false", "ekf:=true", "navsat_transform:=false"
  ]
  pose_estimate_topic: "/odometry/filtered"
  rl_config:
    ekf_odom:
      ros__parameters:
        use_control: false
        odom0: /rgbd_odom
        odom0_config: [false,  false,  false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 20
        odom0_nodelay: false
        odom0_differential: false
        odom0_relative: true

        imu0: /camera/imu
        imu0_config: [false, false, false,
                      false,  false, false,
                      false, false, false,
                      true, true,  true,
                      true,  true,  true]
        #imu0_nodelay: false
        #imu0_differential: false
        #imu0_relative: true
        imu0_queue_size: 60
        imu0_remove_gravitational_acceleration: true